---
title: "Analysis"
author: "Nicolas Banholzer"
date: "2023-07-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "..")
```

## Libraries

```{r libraries}
library(tidyverse)
library(haven)
library(reshape2)
library(rstanarm)
library(brms)
library(tidybayes)
library(ggalluvial)
library(mice)
source("utils/plotting.r")
source("utils/tex.r")
```


## Data

```{r data}
df <- readRDS("data-clean/echo.rds") %>%
  group_by(record_id) %>%
  filter(any(event_time == "Start")) %>%
  ungroup()

all_outcomes <- c(
  "pericard_effusion" = "Pericardial\neffusion",
  "pericard_thickening" = "Pericardial\nthickening",
  "pericardial_calc" = "Pericardial\ncalcification",
  "constriction_sign" = "Signs of\nconstriction",
  "constriction" = "Definitive\nconstriction"
)

nrow(filter(df, event_time == "Start"))
nrow(filter(df, event_time == "End"))
nrow(filter(df, event_time == "Post"))
n_distinct(df$record_id)
```


## Tables

### Table 1

```{r patient-characteristics}
df_base_char <- df %>%
  group_by(record_id) %>%
  slice(1) %>%
  ungroup()

char_vars <- c(
  "Gender" = "sex",
  "Median age (years)" = "age",
  "Site" = "site",
  "BMI (kg/m2)" = "bmi",
  "Obesity (BMI > 30kg/m2)" = "obesity",
  "Underweight (BMI < 18kg/m2)" = "underweight",
  "6min walk-test distance (m)" = "smwt_distance_nr",
  "Sit-to-stand test (repetitions per min)" = "fa_sit_to_stand_nr",
  "Systolic Blood Pressure (mmHg)" = "ce_sys_blpress_nr",
  "Diastolic Blood Pressure (mmHg)" = "ce_dia_blpress_nr",
  "HIV infection status" = "hiv",
  "Median CD4 cell count (mm3)" = "hiv_cd4_mm3_nr",
  "HIV viral load (copies/mL)" = "hiv_viral_load",
  "Relapse TB case" = "tbd_pat_cat",
  "Cavitary disease" = "cavity",
  "TB drug resistance" = "drugresistant",
  "TB manifestation" = "tbd_diagnosis",
  "Smoking" = "sm_smoking_yn",
  "History of hypertension" = "mh_hypertension_yn",
  "Level of CRP (mg/l)" = "lab_creactive_prot_nr",
  "Level of neutrophils (G/I)" = "lab_neutrophils_nr",
  "Level of lymphocytes (G/I)" = "lab_lymphocytes_nr",
  "Level of eosinophiles (G/I)" = "lab_eosinophils_nr",
  "Level of Hb (g/dl)" = "lab_hemoglobin_nr"
)

char_digits <- c(
  "sex" = NA,
  "age" = 0,
  "site" = NA,
  "bmi" = 1,
  "obesity" = NA,
  "smwt_distance_nr" = 0,
  "fa_sit_to_stand_nr" = 0,
  "ce_sys_blpress_nr" = 0,
  "ce_dia_blpress_nr" = 0,
  "hiv" = NA,
  "hiv_cd4_mm3_nr" = 0,
  "hiv_viral_load" = 0,
  "tbd_pat_cat" = NA,
  "cavity" = NA,
  "drugresistant" = NA,
  "tbd_diagnosis" = NA,
  "sm_smoking_yn" = NA,
  "mh_hypertension_yn" = NA,
  "lab_creactive_prot_nr" = 2,
  "lab_neutrophils_nr" = 2,
  "lab_lymphocytes_nr" = 2,
  "lab_eosinophils_nr" = 2,
  "lab_hemoglobin_nr" = 2
)

baseline_tab <- tibble(variable = character(), value = character())

for (var in char_vars) {
  print(var)
  if (is.numeric(df_base_char[[var]])) {
    n_dig <- char_digits[var]
    val <- paste0(
      round_k(median(df_base_char[[var]], na.rm = TRUE), n_dig),
      " (",
      round_k(quantile(df_base_char[[var]], .25, na.rm = TRUE), n_dig),
      " - ",
      round_k(quantile(df_base_char[[var]], .75, na.rm = TRUE), n_dig),
      ")"
    )
    new_row <- tibble(
      variable = names(char_vars)[char_vars == var],
      value = val
    )
  } else if (is.factor(df_base_char[[var]])) {
    counts <- as.numeric(table(df_base_char[[var]]))
    perc_counts <- round(counts / sum(counts) * 100)
    val <- paste0(counts, " (", perc_counts, "%)")
    names_counts <- names(table(df_base_char[[var]]))
    new_row <- tibble(
      variable = c(
        names(char_vars)[char_vars == var],
        paste0("   ", names_counts)
      ),
      value = c("", val)
    )
  } else if (is.character(df_base_char[[var]])) {
    new_row <- tibble(
      variable = c("", names(char_vars)[char_vars == var]),
      value = c("", "")
    )
  } else {
    stop(sprintf("Incorrect variable type for %s", var))
  }
  baseline_tab <- rbind(baseline_tab, new_row)
}

# manually add third subcategory for hiv status
hiv_p <- df_base_char$hiv_cd4_mm3_nr[df_base_char$hiv == "Positive"]
hiv_p <- ifelse(is.na(hiv_p), "Unknown",
  ifelse(hiv_p < 350, "HIV++ (CD4 <350/mm3)", "HIV+ (CD4>=350/mm3)")
)
hiv_p <- factor(
  hiv_p,
  levels = c(
    "HIV++ (CD4 <350/mm3)",
    "HIV+ (CD4>=350/mm3)",
    "Unknown"
  )
)
hiv_p_count <- as.numeric(table(hiv_p))
hiv_p_perc <- round(hiv_p_count / sum(hiv_p_count) * 100, 0)
hiv_p_row <- tibble(
  variable = paste0("      ", levels(hiv_p)),
  value = paste0(hiv_p_count, " (", hiv_p_perc, "%)")
)
hiv_p_row_idx <- which(grepl("Positive", baseline_tab$variable))
baseline_tab <- rbind(
  baseline_tab[1:hiv_p_row_idx, ],
  hiv_p_row,
  baseline_tab[(hiv_p_row_idx + 1):nrow(baseline_tab), ]
)

# manually add HIV-RNA viral load if detectable
nnan_hiv_vl <- !is.na(df_base_char$hiv_viral_load)
det_hiv_vl <- df_base_char$hiv_viral_load == "Detectable"
hiv_viral_load <- df_base_char$hiv_viral_load_nr[nnan_hiv_vl & det_hiv_vl]
hiv_viral_load_val <- paste0(
  round_k(median(hiv_viral_load, na.rm = TRUE), 0),
  " (", round_k(quantile(hiv_viral_load, .25, na.rm = TRUE), 0),
  " - ", round_k(quantile(hiv_viral_load, .75, na.rm = TRUE), 0), ")"
)
hiv_viral_load_row <- tibble(
  variable = paste0("      ", "Median HIV-RNA viral load (copies/mL)"),
  value = hiv_viral_load_val
)
hiv_viral_load_row_idx <- which(grepl("Detectable", baseline_tab$variable))
baseline_tab <- rbind(
  c("variable" = "Variable", "value" = paste0("N=", nrow(df_base_char))),
  baseline_tab[1:hiv_viral_load_row_idx, ],
  hiv_viral_load_row,
  baseline_tab[(hiv_viral_load_row_idx + 1):nrow(baseline_tab), ]
)

write.table(
  data.frame(baseline_tab),
  file = "results/table-1-baseline.txt",
  row.names = FALSE, col.names = FALSE,
  sep = ",", quote = FALSE
)
```


### Table 2

```{r echo-results}
echo_vars <- c(
  "Abnormal LV geometry" = "abnormal_lv_geometry",
  "Type of abnormal LV geometry" = "type_lv_geometry_anomaly",
  "Aortic root dilation" = "aortic_dilation",
  "Ascending aorta dilation" = "asc_aorta_dilation",
  "Relevant aortic valve disease" = "av_disease",
  "   Aortic stenosis" = "as",
  "   Aortic regurgitation" = "ar",
  "Relevant mitral valve disease" = "mv_disease",
  "   Mitral stenosis" = "ms",
  "   Mitral regurgitation" = "mr",
  "Relevant tricuspid valve disease" = "tv_disease",
  "   Tricuspid stenosis" = "ts",
  "   Tricuspid regurgitation" = "tr",
  "LVEF (visually assessed)" = "lvef_visual",
  "LVEF (Simpson BP)" = "lvef_simpson",
  "LV systolic dysfunction" = "lv_systolic_dysfunction",
  "Diastolic dysfunction according to new guidelines" = "diastolic_dysfunction_new",
  "   Type of dysfunction" = "typ_diastolic_dysfunction_new",
  "LV dilation" = "lv_dilatation",
  "LA dilation" = "la_dilation",
  "RV dilation" = "rv_dilation",
  "TAPSE" = "rv_function",
  "TV annulus DTI S'" = "tv_dti",
  "RV FAC" = "fac",
  "RV longitudinal dysfunction" = "rv_long_dysf",
  "RV radial dysfunction" = "rv_rad_dysf",
  "RV/RA Gradient" = "tr_pgmax",
  "RA dilation" = "ra_dilation",
  "Pericardial effusion" = "pericard_effusion",
  "Type of pericardial effusion" = "pericard_effusion_importance",
  "Pericardial thickening" = "pericard_thickening",
  "Pericardial calcification" = "pericardial_calc",
  "Signs of constrictions" = "constriction_sign",
  "Definitive constrictions" = "constriction",
  "Estimated central venous pressure" = "cvp"
)
echo_digits <- c(
  "abnormal_lv_geometry" = NA,
  "type_lv_geometry_anomaly" = NA,
  "aortic_dilation" = NA,
  "asc_aorta_dilation" = NA,
  "av_disease" = NA,
  "as" = NA,
  "ar" = NA,
  "mv_disease" = NA,
  "ms" = NA,
  "mr" = NA,
  "tv_disease" = NA,
  "ts" = NA,
  "tr" = NA,
  "lvef_visual" = 1,
  "lvef_simpson" = 1,
  "lv_systolic_dysfunction" = NA,
  "diastolic_dysfunction_new" = NA,
  "typ_diastolic_dysfunction_new" = NA,
  "lv_dilatation" = NA,
  "la_dilation" = NA,
  "rv_dilation" = NA,
  "rv_function" = 1,
  "tv_dti" = 1,
  "fac" = 1,
  "rv_long_dysf" = NA,
  "rv_rad_dysf" = NA,
  "tr_pgmax" = 1,
  "ra_dilation" = NA,
  "pericard_effusion" = NA,
  "pericard_effusion_importance" = NA,
  "pericard_thickening" = NA,
  "pericardial_calc" = NA,
  "constriction_sign" = NA,
  "constriction" = NA,
  "cvp" = 0
)

echo_tab <- tibble(variable = character(), value = character())

fill_tab <- function(dat, tab) {
  for (var in echo_vars) {
    print(var)
    if (is.numeric(dat[[var]])) {
      n_dig <- echo_digits[var]
      val_med <- round_k(median(dat[[var]], na.rm = TRUE), n_dig)
      val_med <- ifelse((val_med == "NA"), "-", val_med)
      val_low <- round_k(quantile(dat[[var]], .25, na.rm = TRUE), n_dig)
      val_low <- ifelse((val_low == "NA"), "-", val_low)
      val_up <- round_k(quantile(dat[[var]], .75, na.rm = TRUE), n_dig)
      val_up <- ifelse((val_up == "NA"), "-", val_up)
      val <- paste0(val_med, " (", val_low, " - ", val_up, ")")
      new_row <- tibble(
        variable = names(echo_vars)[echo_vars == var],
        value = val
      )
    } else if (is.factor(dat[[var]])) {
      if (length(table(dat[[var]])) == 2) {
        yes_count <- sum(dat[[var]] == "Yes", na.rm = TRUE)
        no_count <- sum(dat[[var]] == "No", na.rm = TRUE)
        tot_count <- yes_count + no_count
        perc_count <- round(yes_count / (yes_count + no_count) * 100, 0)
        perc_count <- ifelse(is.na(perc_count), "", perc_count)
        val <- paste0(yes_count, " / ", tot_count, " (", perc_count, "%)")
        new_row <- tibble(
          variable = names(echo_vars)[echo_vars == var],
          value = val
        )
      } else {
        counts <- as.numeric(table(dat[[var]]))
        perc_counts <- round(counts / sum(counts) * 100)
        perc_counts <- sapply(perc_counts, function(x) ifelse(is.na(x), "", x))
        val <- paste0(counts, " (", perc_counts, "%)")
        names_counts <- paste0("  ", names(table(dat[[var]])))
        new_row <- tibble(variable = names_counts, value = val)
      }
    } else if (is.character(dat[[var]])) {
      new_row <- tibble(
        variable = c("", names(echo_vars)[echo_vars == var]),
        value = c("", "")
      )
    } else {
      print(var)
      stop("Incorrect variable type")
    }
    tab <- rbind(tab, new_row)
  }
  return(tab)
}

echo_tab_base <- fill_tab(
  filter(df, event_time == "Start"),
  echo_tab
)
echo_tab_end <- fill_tab(
  filter(df, event_time == "End"),
  echo_tab
)
echo_tab_post <- fill_tab(
  filter(df, event_time == "Post"),
  echo_tab
)

echo_tab_joint <- cbind(
  echo_tab_base,
  echo_tab_end[, 2],
  echo_tab_post[, 2]
)

echo_tab_joint <- rbind(
  c(
    "Variable",
    paste0(
      "Start of treatment (N=",
      nrow(filter(df, event_time == "Start")),
      ")"
    ),
    paste0(
      "End of treatment (N=",
      nrow(filter(df, event_time == "End")),
      ")"
    ),
    paste0(
      "Post treatment (N=",
      nrow(filter(df, event_time == "Post")),
      ")"
    )
  ),
  echo_tab_joint
)

write.table(
  data.frame(echo_tab_joint),
  file = "results/table-2-echo.txt",
  row.names = FALSE, col.names = FALSE,
  sep = ",", quote = FALSE
)
```

### Supp Tables

```{r echo-by-hiv}
# subgroup at start
# by HIV
echo_tab_base_hiv_pos <- fill_tab(
  filter(df, event_time == "Start", hiv == "Positive"),
  echo_tab
)
echo_tab_base_hiv_neg <- fill_tab(
  filter(df, event_time == "Start", hiv == "Negative"),
  echo_tab
)
echo_tab_base_hiv <- cbind(
  echo_tab_base,
  echo_tab_base_hiv_pos[, 2],
  echo_tab_base_hiv_neg[, 2]
)

echo_tab_base_hiv <- rbind(
  c(
    "Variable",
    paste0(
      "Overall (N=",
      nrow(filter(df, event_time == "Start")),
      ")"
    ),
    paste0(
      "HIV positive (N=",
      nrow(filter(df, event_time == "Start", hiv == "Positive")),
      ")"
    ),
    paste0(
      "HIV negative (N=",
      nrow(filter(df, event_time == "Start", hiv == "Negative")),
      ")"
    )
  ),
  echo_tab_base_hiv
)

write.table(
  data.frame(echo_tab_base_hiv),
  file = "results/table-s1-echo-base-by-hiv.txt",
  row.names = FALSE, col.names = FALSE,
  sep = ",", quote = F
)


# subgroup at end
# by HIV
echo_tab_end_hiv_pos <- fill_tab(
  filter(df, event_time == "End", hiv == "Positive"),
  echo_tab
)
echo_tab_end_hiv_neg <- fill_tab(
  filter(df, event_time == "End", hiv == "Negative"),
  echo_tab
)
echo_tab_end_hiv <- cbind(
  echo_tab_end,
  echo_tab_end_hiv_pos[, 2],
  echo_tab_end_hiv_neg[, 2]
)

echo_tab_end_hiv <- rbind(
  c(
    "Variable",
    paste0(
      "Overall (N=",
      nrow(filter(df, event_time == "End")),
      ")"
    ),
    paste0(
      "HIV positive (N=",
      nrow(filter(df, event_time == "End", hiv == "Positive")),
      ")"
    ),
    paste0(
      "HIV negative (N=",
      nrow(filter(df, event_time == "End", hiv == "Negative")),
      ")"
    )
  ),
  echo_tab_end_hiv
)

write.table(
  data.frame(echo_tab_end_hiv),
  file = "results/table-s2-echo-end-by-hiv.txt",
  row.names = FALSE, col.names = FALSE,
  sep = ",", quote = FALSE
)
```

## Sankey post treatment

```{r sankey-post}
links_post <- df %>%
  group_by(record_id) %>%
  filter(any(event_time == "Post")) %>%
  ungroup() %>%
  dplyr::select(
    record_id,
    event_time,
    pericard_effusion,
    pericard_thickening,
    constriction_sign
  ) %>%
  mutate(
    across(
      c(
        pericard_effusion, pericard_thickening, constriction_sign
      ),
      as.character
    ),
    across(
      c(pericard_effusion, pericard_thickening, constriction_sign),
      ~ ifelse(is.na(.x), "Not determinable", .x)
    ),
    event_time = factor(
      event_time,
      levels = c("Start", "End", "Post")
    )
  ) %>%
  group_by(record_id) %>%
  complete(event_time = levels(event_time)) %>%
  ungroup() %>%
  mutate(
    across(
      c(
        pericard_effusion, pericard_thickening, constriction_sign
      ),
      ~ ifelse(is.na(.x), "Missing follow-up visit", .x)
    )
  ) %>%
  melt(c("record_id", "event_time")) %>%
  rename(outcome = variable) %>%
  mutate(
    outcome = factor(
      outcome %>% fct_recode(
        "Pericardial effusion" = "pericard_effusion",
        "Pericardial thickening" = "pericard_thickening",
        "Signs of constrictions" = "constriction_sign"
      ),
      levels = c(
        "Pericardial effusion",
        "Pericardial thickening",
        "Signs of constrictions"
      )
    ),
    value = factor(value, levels = rev(c(
      "Yes",
      "Not determinable",
      "Missing follow-up visit",
      "No"
    ))),
    event_time = factor(
      event_time,
      levels = c("Start", "End", "Post")
    )
  ) %>%
  group_by(outcome, value, event_time) %>%
  mutate(n = n()) %>%
  ungroup()

links_post %>%
  dplyr::select(-n) %>%
  dcast(record_id + outcome ~ event_time, value.var = "value") %>%
  group_by(outcome, `Start`, `Post`) %>%
  summarize(n = n()) %>%
  ungroup()

flow_post_pl <- links_post %>%
  ggplot(aes(
    x = event_time,
    stratum = value,
    alluvium = record_id,
    fill = value,
    label = value
  )) +
  facet_wrap(~outcome, nrow = 1) +
  geom_flow(stat = "alluvium", lode.guidance = "rightleft") +
  geom_stratum() +
  geom_text(
    stat = "stratum",
    aes(label = after_stat(count)),
    size = 8 / cm(1)
  ) +
  scale_fill_manual(
    values = c(
      wes_palette("FrenchDispatch")[2],
      wes_palette("FrenchDispatch")[3],
      "grey50",
      wes_palette("FrenchDispatch")[4]
    ),
    breaks = c("Yes", "Not determinable", "Missing follow-up visit", "No")
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.01))) +
  labs(x = "Treatment", y = "Number of patients") +
  theme_custom() +
  theme(
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.key.width = unit(0.35, "cm"),
    legend.key.height = unit(0.4, "cm")
  )

save_plot(
  flow_post_pl,
  pdf_file = "results/sankey-post.pdf",
  w = 16, h = 10
)
```

## Pericardial abnormalities

```{r pathologies-proportions}
pericard_pl <- df %>%
  filter(event_time %in% c("Start", "End")) %>%
  dplyr::select(
    event_time,
    pericard_effusion,
    pericard_thickening,
    pericardial_calc,
    constriction_sign,
    constriction
  ) %>%
  set_names(c("event_time", all_outcomes)) %>%
  melt("event_time") %>%
  mutate(
    value = as.character(value),
    value = ifelse(is.na(value), "Not determinable", value),
    value = factor(value, levels = c("No", "Not determinable", "Yes"))
  ) %>%
  group_by(event_time, variable, value) %>%
  summarize(n = n()) %>%
  ungroup() %>%
  group_by(event_time, variable) %>%
  mutate(p = 100 * n / sum(n)) %>%
  ungroup() %>%
  mutate(
    variable = factor(
      variable,
      levels = all_outcomes
    ),
    event_time = factor(
      event_time,
      levels = c("Start", "End")
    )
  ) %>%
  ggplot(aes(x = event_time, y = p, fill = value)) +
  geom_bar(stat = "identity", position = position_stack(), width = .7) +
  facet_wrap(~variable, nrow = 1) +
  labs(y = "Proportion of participants (%)", x = "Treatment") +
  scale_y_continuous(expand = c(0, 0)) +
  scale_fill_manual(
    values = wes_palette("FrenchDispatch")[2:4],
    breaks = c("Yes", "Not determinable", "No")
  ) +
  theme_custom() +
  theme(
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.key.width = unit(0.35, "cm"),
    legend.key.height = unit(0.4, "cm")
  )

save_plot(
  pericard_pl,
  pdf_file = "results/pericardial_pathologies.pdf",
  w = 16, h = 10
)
```

## Any abnormality

```{r any-abnormality}
# all patients
df %>%
  filter(event_time %in% c("Start", "End")) %>%
  rowwise() %>%
  mutate(any_abnorm = any(c_across(names(all_outcomes)) == "Yes")) %>%
  ungroup() %>%
  group_by(event_time) %>%
  summarize(
    n = sum(any_abnorm, na.rm = TRUE),
    N = n(),
    p = n / N
  ) %>%
  ungroup() %>%
  mutate(p = round(p * 100))

# paired patients
df %>%
  filter(event_time %in% c("Start", "End")) %>%
  group_by(record_id) %>%
  filter(n() == 2) %>%
  ungroup() %>%
  rowwise() %>%
  mutate(any_abnorm = any(c_across(names(all_outcomes)) == "Yes")) %>%
  ungroup() %>%
  group_by(event_time) %>%
  summarize(
    n = sum(any_abnorm, na.rm = TRUE),
    N = n(),
    p = n / N
  ) %>%
  ungroup() %>%
  mutate(p = round(p * 100))

# death patients
death_comp <- df %>%
  filter(event_time == "Start") %>%
  group_by(record_id) %>%
  summarize(
    any_abnorm = any(c_across(names(all_outcomes)) == "Yes", na.rm = TRUE),
    death_yn = max(death_yn)
  ) %>%
  ungroup() %>%
  mutate(
    any_abnorm = ifelse(any_abnorm, 1, 0),
    death_yn = ifelse(death_yn == 1, "Yes", "No"),
    death_yn = factor(death_yn, levels = c("No", "Yes"))
  )

table(death_comp$death_yn, death_comp$any_abnorm, useNA = "always")

mod_comp <- glm(
  any_abnorm ~ death_yn,
  family = binomial(),
  data = death_comp
)

summary(mod_comp)
```


## Treatment comparison

### All patients

```{r pericardial-changes}
# subset primary outcomes
df_sub <- df %>%
  filter(event_time %in% c("Start", "End")) %>%
  dplyr::select(
    record_id,
    event_time,
    constriction_sign,
    constriction,
    pericard_effusion,
    pericard_thickening,
    pericardial_calc,
    site,
    age_cat25, sex,
    clindiag, cavity,
    hiv, tbd_pat_cat,
    drugresistant
  ) %>%
  mutate(
    across(c(
      constriction_sign,
      constriction,
      pericard_effusion,
      pericard_thickening,
      pericardial_calc
    ), ~ ifelse(.x == "Yes", 1, 0)),
    event_time = factor(
      event_time,
      levels = c("Start", "End")
    )
  )


# impute data
df_imp <- mice(
  data = dplyr::select(df_sub, -record_id),
  m = 100,
  seed = 12345
)

# estimate models
mod_comp <- list()
for (out in names(all_outcomes)) {
  mod_comp[[out]] <- with(
    df_imp, glm(as.formula(paste0(out, " ~ event_time"))),
    family = binomial()
  )
}

# p-value
pvalue <- function(x) {
  s <- summary(pool(x))
  s$p.value[s$term == "event_timeEnd"]
}

pval <- sapply(mod_comp, pvalue)

write_pvalue <- function(x) {
  if (x < 0.01) {
    return("p<0.01")
  } else {
    return(paste0("p=", round(x, 2)))
  }
}

pval_txt <- sapply(pval, write_pvalue)

# proportion of abnormalities
df_imp_prop <- complete(df_imp, "long") %>%
  dplyr::select(.imp, event_time, names(all_outcomes)) %>%
  melt(c("event_time", ".imp")) %>%
  group_by(.imp, variable, event_time) %>%
  summarise(
    n = sum(value),
    N = n(),
    p = 100 * n / N
  ) %>%
  ungroup() %>%
  group_by(variable, event_time) %>%
  summarise(
    n_m = mean(n),
    n_s = sd(n),
    p_m = mean(p),
    p_s = sd(p)
  ) %>%
  mutate(
    variable = recode(variable, !!!all_outcomes),
    variable = factor(
      variable,
      levels = all_outcomes
    )
  ) %>%
  arrange(variable)

pval_ypos <- df_imp_prop %>%
  mutate(p_pos = p_m + p_s) %>%
  group_by(variable) %>%
  summarize(
    p_pos = max(p_pos)
  ) %>%
  ungroup() %>%
  mutate(p_pos = p_pos + 2.5) %>%
  arrange(variable) %>%
  pull(p_pos)

# plot
pl_comp <- df_imp_prop %>%
  ggplot(aes(x = variable, fill = event_time, y = p_m)) +
  geom_bar(
    stat = "identity",
    position = position_dodge(width = .66),
    width = .5
  ) +
  geom_errorbar(
    aes(ymin = p_m - p_s, ymax = p_m + p_s),
    position = position_dodge(width = .66),
    width = .2
  ) +
  ggsignif::geom_signif(
    annotations = pval_txt,
    y_position = pval_ypos,
    xmin = c(.75, 1.75, 2.75, 3.75, 4.75),
    xmax = c(1.25, 2.25, 3.25, 4.25, 5.25),
    textsize = 8 / cm(1)
  ) +
  scale_y_continuous(
    breaks = scales::breaks_pretty(5),
    expand = expansion(mult = c(0, 0.025))
  ) +
  scale_x_discrete(labels = all_outcomes) +
  scale_fill_manual(
    values = c(
      wes_palette("FrenchDispatch")[2],
      wes_palette("Moonrise3")[2]
    )
  ) +
  coord_cartesian(ylim = c(0, NA), clip = "off") +
  labs(y = "Proportion (%)", x = "Pericardial changes") +
  theme_custom(8) +
  theme(
    legend.position = "bottom", legend.title = element_blank(),
    axis.title.x = element_blank(),
    plot.title = element_text(face = 1, size = 8, margin = margin(b = 20)),
    strip.text = element_text(face = 2),
    legend.key.height = unit(0.3, "cm"),
    legend.key.width = unit(0.5, "cm"),
    plot.margin = margin(l = 20, t = 5.5, b = 5.5, r = 5.5)
  )

save_plot(
  pl_comp,
  pdf_file = "results/pericardial-changes.pdf",
  w = 16, h = 8
)
```

### All patients - complete case analysis

```{r pericardial-changes-fup-complete}
# estimate models
mod_comp_cpl <- list()
for (out in names(all_outcomes)) {
  mod_comp_cpl[[out]] <- with(
    df_sub, glm(as.formula(paste0(out, " ~ event_time"))),
    family = binomial()
  )
}

# p-value
pvalue_unpool <- function(x) {
  s <- coef(summary(x))[, 4]
  s["event_timeEnd"]
}
pval_cpl <- sapply(mod_comp_cpl, pvalue_unpool)
pval_txt_cpl <- sapply(pval_cpl, write_pvalue)

# proportion of abnormalities
df_cpl_prop <- df_sub %>%
  dplyr::select(event_time, names(all_outcomes)) %>%
  melt(c("event_time")) %>%
  group_by(variable, event_time) %>%
  summarise(
    n = sum(value, na.rm = TRUE),
    N = n(),
    p = round(100 * n / N),
    nd = sum(is.na(value)),
    p_nd = round(100 * nd / N)
  ) %>%
  ungroup() %>%
  mutate(
    variable = recode(variable, !!!all_outcomes),
    variable = factor(
      variable,
      levels = all_outcomes
    )
  ) %>%
  arrange(variable)
```

### FUP Patients - paired analysis

```{r pericardial-changes-fup}
# subset primary outcomes
df_sub_fup <- df %>%
  filter(event_time %in% c("Start", "End")) %>%
  group_by(record_id) %>%
  filter(n() == 2) %>%
  ungroup() %>%
  dplyr::select(
    record_id,
    event_time,
    constriction_sign,
    constriction,
    pericard_effusion,
    pericard_thickening,
    pericardial_calc,
    site,
    age_cat25, sex,
    clindiag, cavity,
    hiv, tbd_pat_cat,
    drugresistant
  ) %>%
  mutate(
    across(c(
      constriction_sign,
      constriction,
      pericard_effusion,
      pericard_thickening,
      pericardial_calc
    ), ~ ifelse(.x == "Yes", 1, 0)),
    event_time = factor(
      event_time,
      levels = c("Start", "End")
    )
  )


# impute data
df_imp_fup <- mice(
  data = dplyr::select(df_sub_fup, -record_id),
  m = 100,
  seed = 12345
)

# estimate models
mod_comp_fup <- list()
for (out in names(all_outcomes)) {
  mod_comp_fup[[out]] <- with(
    df_imp_fup, glm(as.formula(paste0(out, " ~ event_time"))),
    family = binomial()
  )
}

# p-value
pval_fup <- sapply(mod_comp_fup, pvalue)
pval_txt_fup <- sapply(pval_fup, write_pvalue)

# proportion of abnormalities
df_imp_fup_prop <- complete(df_imp_fup, "long") %>%
  dplyr::select(.imp, event_time, names(all_outcomes)) %>%
  melt(c("event_time", ".imp")) %>%
  group_by(.imp, variable, event_time) %>%
  summarise(
    n = sum(value),
    N = n(),
    p = 100 * n / N
  ) %>%
  ungroup() %>%
  group_by(variable, event_time) %>%
  summarise(
    n_m = mean(n),
    n_s = sd(n),
    p_m = mean(p),
    p_s = sd(p)
  ) %>%
  mutate(
    variable = recode(variable, !!!all_outcomes),
    variable = factor(
      variable,
      levels = all_outcomes
    )
  ) %>%
  arrange(variable)

# p-value position in plot
pval_ypos_fup <- df_imp_fup_prop %>%
  mutate(p_pos = p_m + p_s) %>%
  group_by(variable) %>%
  summarize(
    p_pos = max(p_pos)
  ) %>%
  ungroup() %>%
  mutate(p_pos = p_pos + 2.5) %>%
  arrange(variable) %>%
  pull(p_pos)

# plot
pl_comp_fup <- df_imp_fup_prop %>%
  ggplot(aes(x = variable, fill = event_time, y = p_m)) +
  geom_bar(
    stat = "identity",
    position = position_dodge(width = .66),
    width = .5
  ) +
  geom_errorbar(
    aes(ymin = p_m - p_s, ymax = p_m + p_s),
    position = position_dodge(width = .66),
    width = .2
  ) +
  ggsignif::geom_signif(
    annotations = pval_txt_fup,
    y_position = pval_ypos_fup,
    xmin = c(.75, 1.75, 2.75, 3.75, 4.75),
    xmax = c(1.25, 2.25, 3.25, 4.25, 5.25),
    textsize = 8 / cm(1)
  ) +
  scale_y_continuous(
    breaks = scales::breaks_pretty(5),
    expand = expansion(mult = c(0, 0.025))
  ) +
  scale_x_discrete(labels = all_outcomes) +
  scale_fill_manual(
    values = c(
      wes_palette("FrenchDispatch")[2],
      wes_palette("Moonrise3")[2]
    )
  ) +
  coord_cartesian(ylim = c(0, NA), clip = "off") +
  labs(y = "Proportion (%)", x = "Pericardial changes") +
  theme_custom(8) +
  theme(
    legend.position = "bottom", legend.title = element_blank(),
    axis.title.x = element_blank(),
    plot.title = element_text(face = 1, size = 8, margin = margin(b = 20)),
    strip.text = element_text(face = 2),
    legend.key.height = unit(0.3, "cm"),
    legend.key.width = unit(0.5, "cm"),
    plot.margin = margin(l = 20, t = 5.5, b = 5.5, r = 5.5)
  )

save_plot(
  pl_comp_fup,
  pdf_file = "results/pericardial-changes-only-follow-up.pdf",
  w = 16, h = 8
)
```

### FUP Patients - paired complete case analysis

```{r pericardial-changes-fup-complete}
# estimate models
mod_comp_fup_cpl <- list()
for (out in names(all_outcomes)) {
  mod_comp_fup_cpl[[out]] <- with(
    df_sub_fup, glm(as.formula(paste0(out, " ~ event_time"))),
    family = binomial()
  )
}

# p-value
pval_fup_cpl <- sapply(mod_comp_fup_cpl, pvalue_unpool)
pval_txt_fup_cpl <- sapply(pval_fup_cpl, write_pvalue)

# proportion of abnormalities
df_fup_cpl_prop <- df_sub_fup %>%
  dplyr::select(event_time, names(all_outcomes)) %>%
  melt(c("event_time")) %>%
  group_by(variable, event_time) %>%
  summarise(
    n = sum(value, na.rm = TRUE),
    N = n(),
    p = round(100 * n / N),
    nd = sum(is.na(value)),
    p_nd = round(100 * nd / N)
  ) %>%
  ungroup() %>%
  mutate(
    variable = recode(variable, !!!all_outcomes),
    variable = factor(
      variable,
      levels = all_outcomes
    )
  ) %>%
  arrange(variable)

df_fup_cpl_prop
```

### Overiew table

```{r overview-table}
out_names <- unname(gsub("\n", " ", all_outcomes))

prop_tbl_cpl_header <- rbind(
  c("", "", "Start of treatment", "", "", "End of treatment", "", "", "Comparison"),
  c("Abnormality", "", "n (%)", "ND (%)", "", "n (%)", "ND (%)", "", "p-value")
)

prop_tbl_cpl_A_name <- paste0(
  "Panel A: Paired analysis of patients with follow-up visits",
  " (N=", n_distinct(df_sub_fup$record_id), ")"
)

prop_tbl_cpl_A <- cbind(
  out_names,
  rep("", length(out_names)),
  paste0(
    pull(filter(df_fup_cpl_prop, event_time == "Start"), n), " (",
    pull(filter(df_fup_cpl_prop, event_time == "Start"), p), "%)"
  ),
  paste0(
    pull(filter(df_fup_cpl_prop, event_time == "Start"), nd), " (",
    pull(filter(df_fup_cpl_prop, event_time == "Start"), p_nd), "%)"
  ),
  rep("", length(out_names)),
  paste0(
    pull(filter(df_fup_cpl_prop, event_time == "End"), n), " (",
    pull(filter(df_fup_cpl_prop, event_time == "End"), p), "%)"
  ),
  paste0(
    pull(filter(df_fup_cpl_prop, event_time == "End"), nd), " (",
    pull(filter(df_fup_cpl_prop, event_time == "End"), p_nd), "%)"
  ),
  rep("", length(out_names)),
  gsub("=", "", gsub("p", "", c(unname(pval_txt_fup_cpl)), fixed = TRUE))
)

prop_tbl_cpl_B_name <- paste0(
  "Panel B: Cross-sectional analysis of all patients",
  " (N=", n_distinct(df_sub$record_id), ")"
)

prop_tbl_cpl_B <- cbind(
  out_names,
  rep("", length(out_names)),
  paste0(
    pull(filter(df_cpl_prop, event_time == "Start"), n), " (",
    pull(filter(df_cpl_prop, event_time == "Start"), p), "%)"
  ),
  paste0(
    pull(filter(df_cpl_prop, event_time == "Start"), nd), " (",
    pull(filter(df_cpl_prop, event_time == "Start"), p_nd), "%)"
  ),
  rep("", length(out_names)),
  paste0(
    pull(filter(df_cpl_prop, event_time == "End"), n), " (",
    pull(filter(df_cpl_prop, event_time == "End"), p), "%)"
  ),
  paste0(
    pull(filter(df_cpl_prop, event_time == "End"), nd), " (",
    pull(filter(df_cpl_prop, event_time == "End"), p_nd), "%)"
  ),
  rep("", length(out_names)),
  gsub("=", "", gsub("p", "", c(unname(pval_txt_cpl)), fixed = TRUE))
)

prop_tbl_cpl <- rbind(
  prop_tbl_cpl_header,
  c(prop_tbl_cpl_A_name, rep("", 8)),
  prop_tbl_cpl_A,
  rep("", 9),
  c(prop_tbl_cpl_B_name, rep("", 8)),
  prop_tbl_cpl_B
)

write.table(
  prop_tbl_cpl,
  file = "results/tbl-pericardial-changes-complete-case-analysis.txt",
  row.names = FALSE, col.names = FALSE,
  sep = ",", quote = FALSE
)

prop_tbl_header <- rbind(
  c("", "", "Start of treatment", "", "", "End of treatment", "", "", "Comparison"),
  c("Abnormality", "", "n (SD)", "% (SD)", "", "n (SD)", "% (SD)", "", "p-value")
)

prop_tbl_A <- cbind(
  out_names,
  rep("", length(out_names)),
  paste0(
    round(pull(filter(df_imp_fup_prop, event_time == "Start"), n_m)), " (",
    round(pull(filter(df_imp_fup_prop, event_time == "Start"), n_s), 1), "%)"
  ),
  paste0(
    round(pull(filter(df_imp_fup_prop, event_time == "Start"), p_m)), " (",
    round(pull(filter(df_imp_fup_prop, event_time == "Start"), p_s), 1), "%)"
  ),
  rep("", length(out_names)),
  paste0(
    round(pull(filter(df_imp_fup_prop, event_time == "End"), n_m)), " (",
    round(pull(filter(df_imp_fup_prop, event_time == "End"), n_s), 1), "%)"
  ),
  paste0(
    round(pull(filter(df_imp_fup_prop, event_time == "End"), p_m)), " (",
    round(pull(filter(df_imp_fup_prop, event_time == "End"), p_s), 1), "%)"
  ),
  rep("", length(out_names)),
  gsub("=", "", gsub("p", "", c(unname(pval_txt_fup)), fixed = TRUE))
)

prop_tbl_B <- cbind(
  out_names,
  rep("", length(out_names)),
  paste0(
    round(pull(filter(df_imp_prop, event_time == "Start"), n_m)), " (",
    round(pull(filter(df_imp_prop, event_time == "Start"), n_s), 1), "%)"
  ),
  paste0(
    round(pull(filter(df_imp_prop, event_time == "Start"), p_m)), " (",
    round(pull(filter(df_imp_prop, event_time == "Start"), p_s), 1), "%)"
  ),
  rep("", length(out_names)),
  paste0(
    round(pull(filter(df_imp_prop, event_time == "End"), n_m)), " (",
    round(pull(filter(df_imp_prop, event_time == "End"), n_s), 1), "%)"
  ),
  paste0(
    round(pull(filter(df_imp_prop, event_time == "End"), p_m)), " (",
    round(pull(filter(df_imp_prop, event_time == "End"), p_s), 1), "%)"
  ),
  rep("", length(out_names)),
  gsub("=", "", gsub("p", "", c(unname(pval_txt)), fixed = TRUE))
)

prop_tbl <- rbind(
  prop_tbl_header,
  c(prop_tbl_cpl_A_name, rep("", 8)),
  prop_tbl_A,
  rep("", 9),
  c(prop_tbl_cpl_B_name, rep("", 8)),
  prop_tbl_B
)

write.table(
  prop_tbl,
  file = "results/tbl-pericardial-changes-imputed-analysis.txt",
  row.names = FALSE, col.names = FALSE,
  sep = ",", quote = FALSE
)
```


## Association with patient characteristics

```{r association-baseline}
# subset primary outcomes
df_sub_fup_wide <- df %>%
  filter(event_time %in% c("Start", "End")) %>%
  group_by(record_id) %>%
  filter(n() == 2) %>%
  ungroup() %>%
  dplyr::select(
    record_id,
    event_time,
    constriction_sign,
    constriction,
    pericard_effusion,
    pericard_thickening,
    pericardial_calc,
    site,
    age_cat25, sex,
    clindiag, cavity,
    hiv, tbd_pat_cat,
    drugresistant
  ) %>%
  mutate(
    across(c(
      constriction_sign,
      constriction,
      pericard_effusion,
      pericard_thickening,
      pericardial_calc
    ), ~ ifelse(.x == "Yes", 1, 0))
  ) %>%
  pivot_wider(
    names_from = event_time,
    values_from = c(
      constriction_sign, constriction,
      pericard_effusion, pericard_thickening,
      pericardial_calc
    ),
    names_sep = "_"
  )



# impute data
df_imp_fup_wide <- mice(
  data = dplyr::select(df_sub_fup_wide, -record_id),
  m = 100,
  seed = 12345
)

# estimate univariable associations
est_assoc <- tibble(
  type = character(),
  time = character(),
  outcome = character(),
  predictor = character(),
  mean = numeric(),
  lower = numeric(),
  upper = numeric()
)

predictors <- c(
  "age_cat25",
  "sex",
  "hiv",
  "clindiag",
  "tbd_pat_cat",
  "cavity",
  "drugresistant"
)

for (out in names(all_outcomes)) {
  # estimate multivariable associations at start of treatment
  mod_mult_start <- with(
    df_imp_fup_wide,
    glm(as.formula(paste0(out, "_Start ~ site + ", paste(predictors, collapse = " + ")))),
    family = binomial()
  )

  mod_sum <- summary(pool(mod_mult_start))
  mean_est <- mod_sum$estimate[-c(1:2)]
  se_est <- mod_sum$std.error[-c(1:2)]

  assoc_mult_start <- tibble(
    type = "Multivariable",
    time = "Start",
    outcome = out,
    predictor = predictors,
    mean = exp(mean_est),
    lower = exp(mean_est - qnorm(.975) * se_est),
    upper = exp(mean_est + qnorm(.975) * se_est)
  )

  est_assoc <- rbind(est_assoc, assoc_mult_start)

  # estimate multivariable associations at end of treatment
  mod_mult_end <- with(
    df_imp_fup_wide,
    glm(as.formula(paste0(out, "_End ~ site + ", out, "_Start + ", paste(predictors, collapse = " + ")))),
    family = binomial()
  )

  mod_sum <- summary(pool(mod_mult_end))
  mean_est <- mod_sum$estimate[-c(1:3)]
  se_est <- mod_sum$std.error[-c(1:3)]

  assoc_mult_end <- tibble(
    type = "Multivariable",
    time = "End",
    outcome = out,
    predictor = predictors,
    mean = exp(mean_est),
    lower = exp(mean_est - qnorm(.975) * se_est),
    upper = exp(mean_est + qnorm(.975) * se_est)
  )

  est_assoc <- rbind(est_assoc, assoc_mult_end)

  for (pred in predictors) {
    # estimate univariable association at start of treatment
    mod <- with(
      df_imp_fup_wide,
      glm(as.formula(paste0(out, "_Start ~ site + ", pred))),
      family = binomial()
    )

    coef_name <- paste0(pred, levels(df[[pred]])[2])
    mod_sum <- summary(pool(mod))
    mean_est <- mod_sum$estimate[mod_sum$term == coef_name]
    se_est <- mod_sum$std.error[mod_sum$term == coef_name]

    assoc_start <- tibble(
      type = "Univariable",
      time = "Start",
      outcome = out,
      predictor = pred,
      mean = exp(mean_est),
      lower = exp(mean_est - qnorm(.975) * se_est),
      upper = exp(mean_est + qnorm(.975) * se_est)
    )

    est_assoc <- rbind(est_assoc, assoc_start)

    # estimate association at end of treatment
    mod <- with(
      df_imp_fup_wide,
      glm(as.formula(paste0(out, "_End ~ site + ", out, "_Start +", pred))),
      family = binomial()
    )

    coef_name <- paste0(pred, levels(df[[pred]])[2])
    mod_sum <- summary(pool(mod))
    mean_est <- mod_sum$estimate[mod_sum$term == coef_name]
    se_est <- mod_sum$std.error[mod_sum$term == coef_name]

    assoc_end <- tibble(
      type = "Univariable",
      time = "End",
      outcome = out,
      predictor = pred,
      mean = exp(mean_est),
      lower = exp(mean_est - qnorm(.975) * se_est),
      upper = exp(mean_est + qnorm(.975) * se_est)
    )

    est_assoc <- rbind(est_assoc, assoc_end)
  }
}

pred_names <- c(
  "<25y",
  "Female",
  "HIV+",
  "Clin. diagnosed",
  "Relapse",
  "Cavitation",
  "MDR"
)

names(pred_names) <- predictors

out_names <- gsub("\n", " ", all_outcomes)

est_assoc <- est_assoc %>%
  mutate(
    predictor = recode(predictor, !!!pred_names),
    outcome = recode(outcome, !!!out_names),
    outcome = factor(
      outcome,
      levels = out_names
    ),
    predictor = factor(
      predictor,
      levels = rev(pred_names)
    ),
    time = factor(
      paste(time, "of treatment"),
      levels = paste(c("Start", "End"), "of treatment")
    ),
    type = factor(
      paste(type, "analysis"),
      levels = paste(c("Univariable", "Multivariable"), "analysis")
    )
  )

# plot
pl_assoc <- est_assoc %>%
  ggplot(aes(
    x = mean,
    xmin = lower,
    xmax = upper,
    y = predictor,
    color = type
  )) +
  facet_grid(outcome ~ time) +
  geom_vline(
    aes(xintercept = 1),
    linetype = "dotted", color = "grey30"
  ) +
  geom_errorbar(
    width = .5,
    position = position_dodge(width = .66)
  ) +
  geom_point(
    shape = 23, size = 1, fill = "white",
    position = position_dodge(width = .66),
  ) +
  scale_x_continuous(
    limits = c(0, NA),
    expand = c(0, 0)
  ) +
  scale_color_manual(
    values = wes_palette("Darjeeling2")[c(2, 5)]
  ) +
  labs(x = "Odds ratio") +
  theme_custom() +
  theme(
    axis.title.y = element_blank(),
    strip.text.x = element_text(face = 2, margin = margin(b = 10, t = 10)),
    legend.position = "bottom",
    legend.title = element_blank(),
    panel.spacing.y = unit(0.5, "lines")
  ) +
  guides(color = guide_legend(nrow = 1))

save_plot(
  pl_assoc,
  pdf_file = "results/association.pdf",
  w = 16, h = 23
)

est_assoc %>%
  mutate_if(is.numeric, round, 2) %>%
  arrange(type, time, outcome, predictor) %>%
  writexl::write_xlsx("results/association.xlsx")
```